version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - relayer
  relayer:
    build:
      context: .
      dockerfile: docker/Dockerfile.relayer
    environment:
      - GOERLI_RPC_URL=${GOERLI_RPC_URL}
      - MUMBAI_RPC_URL=${MUMBAI_RPC_URL}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - BRIDGE_ETH_ADDRESS=${BRIDGE_ETH_ADDRESS}
      - BRIDGE_POLY_ADDRESS=${BRIDGE_POLY_ADDRESS}
